import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@Components/NavigationBar/Navigation";

export const metadata: Metadata = {
  title: "Next js App in Here",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = (props: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className="bg-white prose prose-stone border-0 border-black min-h-screen max-w-full">
        <Navigation />
        <header>{/* Header Goes Here */}</header>
        <article>{props.children}</article>
        <footer>{/* Footer Goes Here */}</footer>
      </body>
    </html>
  );
};

export default RootLayout;
